# Site settings
title: Swift makes me happy
email: ever8greener@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Anything will be posted here when it comes to SWIFT development. I am currently working on a musical application. code snippets, libraries, extensions and tutorials.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ever8green
github_username:  hallomuze

# Build settings
markdown: kramdown
